apiVersion: v1
kind: Pod
metadata:
  name: configmap-vol-demo
  labels:
    app: configmap-demo
spec:
  containers:
  - name: app
    image: nginx:1.27
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: app-config
  restartPolicy: Never
